### ISSUE TITLE
Similar package

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/fullscreen#1]
Hi, I made a package that also uses `screenfull.js`, [`shinyfullscreen`](https://cran.r-project.org/web/packages/shinyfullscreen/index.html). I just wanted to draw your attention on that, to avoid duplicated packages. 

If you already saw it and decided to make you own package anyway, there's no problem at all on my side ;)

**Comment by JohnCoene** [comment]
Oh shoot, I had not noticed!

I'll take a look and link to your repo when I'm back from holidays

**Comment by JohnCoene** [comment]
Linking to your repo, archiving this.
